export const ADD_AMBULANCE_FACILITY_REQUEST = 'ADD_AMBULANCE_FACILITY_REQUEST';
export const ADD_AMBULANCE_FACILITY_SUCCESS = 'ADD_AMBULANCE_FACILITY_SUCCESS';
export const ADD_AMBULANCE_FACILITY_FAILURE = 'ADD_AMBULANCE_FACILITY_FAILURE';
