export const GET_DRIVER_WITHOUT_AMBULANCE_REQUEST = 'GET_DRIVER_WITHOUT_AMBULANCE_REQUEST';
export const GET_DRIVER_WITHOUT_AMBULANCE_SUCCESS = 'GET_DRIVER_WITHOUT_AMBULANCE_SUCCESS';
export const GET_DRIVER_WITHOUT_AMBULANCE_FAILURE = 'GET_DRIVER_WITHOUT_AMBULANCE_FAILURE';

export const REGISTERED_AMBULANCE_REQUEST = 'REGISTERED_AMBULANCE_REQUEST';
export const REGISTERED_AMBULANCE_SUCCESS = 'REGISTERED_AMBULANCE_SUCCESS';
export const REGISTERED_AMBULANCE_FAILURE = 'REGISTERED_AMBULANCE_FAILURE';
