export const ADD_FACILITY_REQUEST = 'ADD_FACILITY_REQUEST';
export const ADD_FACILITY_SUCCESS = 'ADD_FACILITY_SUCCESS';
export const ADD_FACILITY_FAILURE = 'ADD_FACILITY_FAILURE';

export const GET_ALL_HEALTHCARE_FACILITIES_REQUEST = 'GET_ALL_HEALTHCARE_FACILITIES_REQUEST';
export const GET_ALL_HEALTHCARE_FACILITIES_SUCCESS = 'GET_ALL_HEALTHCARE_FACILITIES_SUCCESS';
export const GET_ALL_HEALTHCARE_FACILITIES_FAILURE = 'GET_ALL_HEALTHCARE_FACILITIES_FAILURE';

export const GET_HEALTHCARE_FACILITY_REQUEST = 'GET_HEALTHCARE_FACILITY_REQUEST';
export const GET_HEALTHCARE_FACILITY_SUCCESS = 'GET_HEALTHCARE_FACILITY_SUCCESS';
export const GET_HEALTHCARE_FACILITY_FAILURE = 'GET_HEALTHCARE_FACILITY_FAILURE';
