export const ADD_FACILITY_REQUEST = 'ADD_FACILITY_REQUEST';
export const ADD_FACILITY_SUCCESS = 'ADD_FACILITY_SUCCESS';
export const ADD_FACILITY_FAILURE = 'ADD_FACILITY_FAILURE';

export const GET_ALL_HEALTHCARE_FACILITIES_REQUEST = 'GET_ALL_HEALTHCARE_FACILITIES_REQUEST';
export const GET_ALL_HEALTHCARE_FACILITIES_SUCCESS = 'GET_ALL_HEALTHCARE_FACILITIES_SUCCESS';
export const GET_ALL_HEALTHCARE_FACILITIES_FAILURE = 'GET_ALL_HEALTHCARE_FACILITIES_FAILURE';

export const GET_HOSPITAL_INFO_REQUEST = 'GET_HOSPITAL_INFO_REQUEST';
export const GET_HOSPITAL_INFO_SUCCESS = 'GET_HOSPITAL_INFO_SUCCESS';
export const GET_HOSPITAL_INFO_FAILURE = 'GET_HOSPITAL_INFO_FAILURE';
