export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const RIDER_SIGNUP_REQUEST = 'RIDER_SIGNUP_REQUEST';
export const RIDER_SIGNUP_SUCCESS = 'RIDER_SIGNUP_SUCCESS';
export const RIDER_SIGNUP_FAILURE = 'RIDER_SIGNUP_FAILURE';

export const DRIVER_SIGNUP_REQUEST = 'DRIVER_SIGNUP_REQUEST';
export const DRIVER_SIGNUP_SUCCESS = 'DRIVER_SIGNUP_SUCCESS';
export const DRIVER_SIGNUP_FAILURE = 'DRIVER_SIGNUP_FAILURE';

export const GET_HOSPITAL_BY_CITY_REQUEST = "GET_HOSPITAL_BY_CITY_REQUEST";
export const GET_HOSPITAL_BY_CITY_SUCCESS = "GET_HOSPITAL_BY_CITY_SUCCESS";
export const GET_HOSPITAL_BY_CITY_FAILURE = "GET_HOSPITAL_BY_CITY_FAILURE";

export const GET_AMBULANCE_NEAR_USER_REQUEST = "GET_AMBULANCE_NEAR_USER_REQUEST";
export const GET_AMBULANCE_NEAR_USER_SUCCESS = "GET_AMBULANCE_NEAR_USER_SUCCESS";
export const GET_AMBULANCE_NEAR_USER_FAILURE = "GET_AMBULANCE_NEAR_USER_FAILURE";

export const USER_BOOKING_REQUEST = 'USER_BOOKING_REQUEST';
export const USER_BOOKING_SUCCESS = 'USER_BOOKING_SUCCESS';
export const USER_BOOKING_FAILURE = 'USER_BOOKING_FAILURE';

